apiVersion: apps/v1
kind: Deployment
metadata:
  name: approval-app
  labels:
    app: approval-app
    pipecd.dev/variant: primary
spec:
  replicas: 4
  selector:
    matchLabels:
      app: approval-app
      pipecd.dev/variant: primary
  template:
    metadata:
      labels:
        app: approval-app
        pipecd.dev/variant: primary
    spec:
      containers:
      - name: main
        image: nginx:1.27
        ports:
        - containerPort: 80
        env:
        - name: APPROVAL_REQUIRED
          value: "true"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"