apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluegreen-app
  labels:
    app: bluegreen-app
    pipecd.dev/variant: primary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bluegreen-app
      pipecd.dev/variant: primary
  template:
    metadata:
      labels:
        app: bluegreen-app
        pipecd.dev/variant: primary
    spec:
      containers:
      - name: main
        image: nginx:1.27
        ports:
        - containerPort: 80
        env:
        - name: COLOR
          value: "blue"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"